import { LineProfile, Perfume } from './perfume.model';

export const LINES: readonly LineProfile[] = [
  {
    line: 'hombre',
    path: '/perfumes/hombre',
    label: 'Perfumes para hombre',
    descriptor: 'Homme',
    sloganLead: 'El lujo y la elegancia',
    slogan: 'en cada gota.',
    lede: 'Ámbar, oud y especia. La selección masculina de la casa, en concentraciones que aguantan el día entero.',
    metaDescription:
      'Perfumes árabes para hombre en Cochabamba: Lattafa, Armaf, Rasasi, Afnan y Al Haramain. Eau de parfum original, precios en bolivianos.',
    rosegold: false,
  },
  {
    line: 'mujer',
    path: '/perfumes/mujer',
    label: 'Perfumes para mujer',
    descriptor: 'Femme',
    sloganLead: 'La elegancia',
    slogan: 'se lleva en la piel.',
    lede: 'Floral, frutal y almizcle. La línea femenina de la casa, elegida por su estela antes que por su nombre.',
    metaDescription:
      'Perfumes árabes para mujer en Cochabamba: Lattafa Yara, Rasasi Hawas, Armaf Club de Nuit y más. Eau de parfum original, precios en bolivianos.',
    rosegold: true,
  },
];

export const PERFUMES: readonly Perfume[] = [
  {
    slug: 'khamrah',
    name: 'Khamrah',
    brand: 'Lattafa',
    line: 'hombre',
    family: 'Oriental gourmand',
    notes: ['Canela', 'Dátil', 'Praliné', 'Vainilla', 'Benjuí'],
    sizeMl: 100,
    priceBob: 380,
    concentration: 'Eau de parfum',
    summary: 'Dátil y canela sobre un fondo de vainilla tostada.',
    description:
      'La casa lo vende más que ningún otro. Abre dulce y especiado, con el dátil por delante, y termina en una base de benjuí y vainilla que se queda en la ropa hasta el día siguiente. Para la noche fría de Cochabamba.',
    featured: true,
    inStock: true,
    order: 10,
    photo: '/img/perfumes/9pm.webp',
  },
  {
    slug: 'club-de-nuit-intense-man',
    name: 'Club de Nuit Intense Man',
    brand: 'Armaf',
    line: 'hombre',
    family: 'Amaderado afrutado',
    notes: ['Piña', 'Limón', 'Abedul', 'Jazmín', 'Ámbar gris'],
    sizeMl: 105,
    priceBob: 420,
    concentration: 'Eau de toilette',
    summary: 'Piña y abedul, la firma que todo el mundo reconoce.',
    description:
      'El más pedido de Armaf y la puerta de entrada a la perfumería árabe. La piña de la salida da paso a un abedul ahumado sobre ámbar gris. Proyecta mucho: media aplicación basta.',
    featured: true,
    inStock: true,
    order: 20,
    photo: '/img/perfumes/club-de-nuit-intense-man.webp',
  },
  {
    slug: 'asad',
    name: 'Asad',
    brand: 'Lattafa',
    line: 'hombre',
    family: 'Amaderado especiado',
    notes: ['Pimienta negra', 'Café', 'Piña', 'Vainilla', 'Cedro'],
    sizeMl: 100,
    priceBob: 320,
    concentration: 'Eau de parfum',
    summary: 'Café y pimienta negra sobre cedro seco.',
    description:
      'Seco, amargo y masculino sin esfuerzo. El café domina la primera hora y el cedro sostiene el resto. Rinde de sobra para oficina y para salida.',
    featured: false,
    inStock: true,
    order: 30,
    photo: '/img/perfumes/club-de-nuit-intense-man.webp',
  },
  {
    slug: 'hawas-for-him',
    name: 'Hawas For Him',
    brand: 'Rasasi',
    line: 'hombre',
    family: 'Fougère acuático',
    notes: ['Bergamota', 'Manzana', 'Canela', 'Ámbar', 'Almizcle'],
    sizeMl: 100,
    priceBob: 560,
    concentration: 'Eau de parfum',
    summary: 'Fresco y limpio, con una canela discreta detrás.',
    description:
      'El más versátil de la selección masculina. Acuático y afrutado en la salida, con una canela que sólo aparece a media tarde. El que se regala cuando no se conoce el gusto de la persona.',
    featured: false,
    inStock: true,
    order: 40,
    photo: '/img/perfumes/hawas-for-him.webp',
  },
  {
    slug: '9pm',
    name: '9PM',
    brand: 'Afnan',
    line: 'hombre',
    family: 'Oriental ambarado',
    notes: ['Manzana', 'Lavanda', 'Canela', 'Vainilla', 'Haba tonka'],
    sizeMl: 100,
    priceBob: 340,
    concentration: 'Eau de parfum',
    summary: 'Manzana y lavanda con una base de tonka y vainilla.',
    description:
      'Pensado para la noche y honesto con su nombre. La lavanda le quita el exceso de dulzor a la manzana y la haba tonka cierra en cálido. Relación precio y rendimiento difícil de igualar.',
    featured: false,
    inStock: true,
    order: 50,
    photo: '/img/perfumes/9pm.webp',
  },
  {
    slug: 'l-aventure',
    name: "L'Aventure",
    brand: 'Al Haramain',
    line: 'hombre',
    family: 'Amaderado aromático',
    notes: ['Bergamota', 'Canela', 'Ámbar', 'Vetiver', 'Pachulí'],
    sizeMl: 100,
    priceBob: 300,
    concentration: 'Eau de parfum',
    summary: 'Ámbar y vetiver, sobrio de principio a fin.',
    description:
      'La opción sobria de la línea. Sin salida dulce y sin estridencias: bergamota, ámbar y un vetiver terroso que aguanta la jornada. Para quien no quiere que su perfume entre antes que él.',
    featured: false,
    inStock: true,
    order: 60,
    photo: '/img/perfumes/hawas-for-him.webp',
  },
  {
    slug: 'yara',
    name: 'Yara',
    brand: 'Lattafa',
    line: 'mujer',
    family: 'Floral gourmand',
    notes: ['Orquídea', 'Heliotropo', 'Vainilla', 'Almizcle', 'Sándalo'],
    sizeMl: 100,
    priceBob: 290,
    concentration: 'Eau de parfum',
    summary: 'Orquídea y vainilla, dulce y reconocible.',
    description:
      'El femenino más vendido de la casa y el que más gente pregunta por su nombre en la calle. Dulce sin empalagar, con un almizcle que lo sostiene toda la tarde.',
    featured: true,
    inStock: true,
    order: 10,
    photo: '/img/perfumes/club-de-nuit-woman.webp',
  },
  {
    slug: 'hawas-for-her',
    name: 'Hawas For Her',
    brand: 'Rasasi',
    line: 'mujer',
    family: 'Floral afrutado',
    notes: ['Pera', 'Grosella negra', 'Jazmín', 'Ámbar', 'Almizcle'],
    sizeMl: 100,
    priceBob: 540,
    concentration: 'Eau de parfum',
    summary: 'Pera y grosella sobre jazmín y ámbar.',
    description:
      'La versión femenina del Hawas, y la más elegante de la línea. Afrutada en la salida, floral en el corazón y ambarada en el fondo. Va igual de bien a la oficina que a una boda.',
    featured: true,
    inStock: true,
    order: 20,
    photo: '/img/perfumes/blue-lady-2.webp',
  },
  {
    slug: 'club-de-nuit-woman',
    name: 'Club de Nuit Woman',
    brand: 'Armaf',
    line: 'mujer',
    family: 'Chipre floral',
    notes: ['Grosella negra', 'Pera', 'Rosa', 'Pachulí', 'Vainilla'],
    sizeMl: 105,
    priceBob: 400,
    concentration: 'Eau de toilette',
    summary: 'Rosa y pachulí con un fondo afrutado.',
    description:
      'Chipre clásico leído en clave árabe. La rosa y el pachulí le dan carácter y la pera evita que resulte severo. El femenino de mayor proyección del catálogo.',
    featured: false,
    inStock: true,
    order: 30,
    photo: '/img/perfumes/club-de-nuit-woman.webp',
  },
  {
    slug: 'ameerati',
    name: 'Ameerati',
    brand: 'Lattafa',
    line: 'mujer',
    family: 'Floral frutal',
    notes: ['Frutas rojas', 'Jazmín', 'Vainilla', 'Almizcle blanco'],
    sizeMl: 100,
    priceBob: 280,
    concentration: 'Eau de parfum',
    summary: 'Frutas rojas y jazmín, para el día.',
    description:
      'Ligero, fresco y sin pretensiones. El que se usa a diario y no cansa. Buen primer perfume árabe para quien viene de fragancias comerciales.',
    featured: false,
    inStock: true,
    order: 40,
    photo: '/img/perfumes/club-de-nuit-woman.webp',
  },
  {
    slug: 'najdia',
    name: 'Najdia',
    brand: 'Lattafa',
    line: 'mujer',
    family: 'Floral almizclado',
    notes: ['Durazno', 'Rosa', 'Almizcle blanco', 'Ámbar'],
    sizeMl: 100,
    priceBob: 260,
    concentration: 'Eau de parfum',
    summary: 'Durazno y rosa sobre almizcle blanco.',
    description:
      'Suave y cercano, de los que se perciben a un brazo de distancia y no más. Pensado para oficina y para clima cálido, donde un ambarado pesaría.',
    featured: false,
    inStock: true,
    order: 50,
    photo: '/img/perfumes/blue-lady-2.webp',
  },
  {
    slug: 'blue-lady-2',
    name: 'Blue Lady 2',
    brand: 'Rasasi',
    line: 'mujer',
    family: 'Floral frutal',
    notes: ['Bergamota', 'Melocotón', 'Jazmín', 'Sándalo', 'Almizcle'],
    sizeMl: 75,
    priceBob: 310,
    concentration: 'Eau de parfum',
    summary: 'Melocotón y jazmín con base de sándalo.',
    description:
      'Un clásico de Rasasi que lleva décadas vendiéndose. Frutal luminoso arriba, sándalo cremoso abajo. El femenino más pedido por las clientas mayores de la casa.',
    featured: false,
    inStock: true,
    order: 60,
    photo: '/img/perfumes/blue-lady-2.webp',
  },
];
